### ISSUE TITLE
Update Meow and Edible Scratch translations

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchr2_translations#10]
The about and developers pages have been updated to remove `FormattedHTMLMessage`. The Meow (`cat.json`) and Edible Scratch (`yum.json`) files need to be updated with the new default English strings from the corresponding `l10n.json` files.

Originally reported:
https://github.com/LLK/scratch-www/issues/1772

**Comment by Narulacodes** [comment]
I know @kenny2github is planned to do this, but may i take this?

**Comment by Kenny2github** [comment]
I’ll get to this once I have my environment set up :)
