### ISSUE TITLE
Several incorrect strings in French

### ISSUE THREAD

**Issue by NilsTheBest** [LLK/scratchr2_translations#20]
The translation on the profiles is wrong:
![screen shot 2018-07-29 at 00 40 40](https://user-images.githubusercontent.com/41824646/43361168-6ebe6dfc-92c8-11e8-8163-081089ad2096.png)
"ago" is never used in French.
Should be: "Inscrit il y a (amount of time)"

Second error:
![screen shot 2018-07-29 at 00 48 49](https://user-images.githubusercontent.com/41824646/43361211-74ea4e66-92c9-11e8-8542-d76fab270f6b.png)
"commenter l'activité" means "to comment activity".
"comment activity" should've been instead: "activité de commentaires" (the closest thing)

![screen shot 2018-07-29 at 01 12 43](https://user-images.githubusercontent.com/41824646/43361351-bdfe761a-92cc-11e8-9657-e668d258a4cd.png)
This is also (very) incorrect, it should've been "Il y a (time)"

Hope this helps

**Comment by Kenny2github** [comment]
Please go to the [Scratch Website Transifex project](https://www.transifex.com/llk/scratch-website/dashboard/) to change translations in languages other than English. This repository only pulls translations from Transifex.

**Comment by NilsTheBest** [comment]
Got it. Thanks.

**Comment by NilsTheBest** [comment]
@Kenny2github  Concerning the key messages\.activityComments, since I am new to the interface, I submitted the original (bad) translation for suggestion, rather than the correct translation, however the interface does not seem to let me close my suggestion and replace it with the one I intended.  I left a comment about this on the key. Is this something you could cancel so I can submit the correct text? Thanks.

**Comment by Kenny2github** [comment]
I don't have control over translations (I only translate to Chinese, not French, and I don't have reviewing power there either), but you should be able to change your suggested translation and just resubmit it.

**Comment by NilsTheBest** [comment]
I have tried it already, it should work, hopefully
